### PR TITLE
Ommers validation fix

### PR DESCRIPTION
**Pull request by LukasGasior1**
TODO: test case

### CODE REVIEW

**Comment by rtkaczyk** [comment]
Yep, the fix obviously looks good. Test case in `BlockImportSpec` would be nice

**Comment by LukasGasior1** [comment]
It turns out it's not that straightforward to test it. Currently we use mock validators impl in `BlockImportSpec`. How about a task in YT for that? @rtkaczyk @mcsherrylabs

**Comment by rtkaczyk** [comment]
I'd be happy with a YT task

**Comment by LukasGasior1** [comment]
EC-364

**Pull request merged**
