### PR TITLE
fix configs

### PR DESCRIPTION
**Pull request by KonradStaniec**
eth and ropsten don not have concept of eras, so 1st era should last as long as possible 50 000 000 block is around 21 years.

### CODE REVIEW

**Comment by mmrozek** [comment]
If they don't have such concepts maybe a better idea is to keep the configuration file as is and handle this case in `MonetaryPolicyConfig` class (ex. if this parameter doesn't exist, we could set max value)

**Comment by KonradStaniec** [comment]
i do not know if it worth now spliting `MonetaryPolicyConfig` to two or more classes, and then refactoring our reward calcluator to accomodate that. But maybe i will just switch this value to `Integer.MaxValue` in config ? I mean everywhere else we are using this convention.

**Comment by mmrozek** [comment]
I agree with you. I have the same in mind. Just simple checking if `era-duration` exists, if not set to `Integer.MaxValue`. You could also add a comment why. I think it will be clean enough solution.

**Comment by KonradStaniec** [comment]
Yep it would be good, but as currently stands `era-duration` will be always present, as all configs inherit it from base config, solution to that is to remove monetary policy from base, and define separatly in each config, but this is quite repetetive so i am not sure it worth it.

**Pull request merged**
