### PR TITLE
[CGKIELE-110] Externalise Protobuf API

### PR DESCRIPTION
**Pull request by rtkaczyk**

### CODE REVIEW

**Comment by rtkaczyk** [comment]
Whoever is reviewing this one, please try to checkout the branch and and run:

```
git submodule init
git submodule update
sbt testOnly *extvm*
```

(I've had some major issues with the submodule)

**Comment by loverdos** [comment]
I am on it

**Comment by loverdos** [comment]
My procedure so far, while I am waiting for the tests to finish:
```
$ git submodule update --init
$ sbt 'testOnly *extvm*'
```

Let's see...

**Comment by loverdos** [comment]
OK, that was fast:

```
[info] Run completed in 3 seconds, 20 milliseconds.
[info] Total number of tests run: 14
[info] Suites: completed 4, aborted 0
[info] Tests: succeeded 14, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 14, Failed 0, Errors 0, Passed 14
[success] Total time: 160 s, completed Mar 9, 2018 2:44:24 PM
```

LGTM

**Pull request merged**
