### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by lemastero**
# Description

Update library dependencies. (This is #685 but with signed commits.)

# Proposed Solution

# Important Changes Introduced

# Testing

Tested by: `sbt clean test`

### CODE REVIEW

**Comment by lemastero** [comment]
cc @kapke @mmrozek

**Review by mmrozek — APPROVED** [review]
lgtm

**Review by kapke — APPROVED** [review]
LGTM!

**Comment by lemastero** [comment]
This PR is replaced by #704. PR opened from fork did not trigger CI action properly.

**Pull request closed without merging**
