### PR TITLE
[EC-327] Fix minor linter issues

### PR DESCRIPTION
**Pull request by mirkoAlic**
Minor fixes:

- Unused method parameter: 'peerId'
- Unused imports

### CODE REVIEW

**Comment by LukasGasior1** [comment]
I have mixed feelings about adding 'final' to our case classes, do we really need it? (hey, we all know we shouldn't extend them)

**Comment by mirkoAlic** [comment]
I agree with you but as it's an open source project, is better follow the standard style checks, also the linter's report gave a better output (less verbose) and made the analysis easier. We can either do this now, leave it for later or even disable the rule, what do you think?

**Comment by rtkaczyk** [comment]
I'm all for disabling that rule!

**Comment by rtkaczyk** [comment]
> Implicit definitions must have an explicit type ascription

Why?

**Comment by mirkoAlic** [comment]
You are right is not necessary, I rechecked the rule, and I noticed that for these situations it can't be possible that the compiler has troubles. I'll revert that commit too.

**Comment by mirkoAlic** [comment]
Changes are ready!

**Pull request merged**
