### PR TITLE
[Chore] Single line for message logging

### PR DESCRIPTION
**Pull request by ntallar**
# Description

As we are currently logging all messages, it can be a bit of a pain to read logs with all the structures being printed as multiline, this changes for them being single line.

(my first thought was removing that logging entirely, but it ended up being useful for tracking blocks on the testnet)

# Testing

Checking that I didn't miss any structure or message

### CODE REVIEW

**Comment by mirkoAlic** [comment]
I think there are still some multiline messages (i search by `stripMargin`).. what about these ones?
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/domain/Receipt.scala
- src/main/scala/io/iohk/ethereum/domain/Block.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/ImportMessages.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/SyncSchedulerActorState.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala

**Comment by ntallar** [comment]
>src/main/scala/io/iohk/ethereum/blockchain/sync/SyncSchedulerActorState.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
src/main/scala/io/iohk/ethereum/ledger/BlockPreparator.scala

I addressed all but these, as they are not structure/message logs nor they have been a nuisance to me when running Mantis locally

**Comment by mirkoAlic** [comment]
> > src/main/scala/io/iohk/ethereum/blockchain/sync/SyncSchedulerActorState.scala
> > src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
> > src/main/scala/io/iohk/ethereum/ledger/BlockPreparator.scala
> 
> I addressed all but these, as they are not structure/message logs nor they have been a nuisance to me when running Mantis locally, but I can change them if you prefer

fair enough.

**Review by mirkoAlic — APPROVED** [review]

**Comment by mmrozek** [comment]
Just curious: what is wrong with multiline logs? We have already implemented `logging.json-output` to use with graylog

**Comment by ntallar** [comment]
That locally I like running Mantis with logging.json-output set to false :stuck_out_tongue:  this change is not for the testnet but for me or anyone that runs Mantis locally with that disabled (and it doesn't affect those who don't disable it)

**Pull request merged**
